### PR TITLE
feat: support of Tact 1.5.2

### LINKED ISSUE #44: Support Tact 1.5.0
Full changelog for Tact v1.5.0: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md#150---2024-09-15

### New Tact features

- `asm` functions: `asm fun keccak256(s: Slice): Int { 1 INT HASHEXT_KECCAK256 }`;
- Wider range of serialization options for integers — `uint1` through `uint256` and `int1` through `int257`: `counter: Int as uint48`;
- Allow omitting last semicolons in contract/trait declarations and definitions: `trait Test { abstract fun foo() }` -- the semicolon after `foo()` is not required anymore.

### New builtin and stdlib functions and methods

- The `exists` method for the `Map` type: `m.exists(key)`, equivalent to `m.get(key) != null`;
- The `deepEquals` method for the `Map` type: `m1.deepEquals(m2)`;
- The `toSlice` method for structs and messages: `struct.toSlice()`;
- The `storeBit` method for `Builder` type and the `loadBit` method for `Slice` type (aliases for `storeBool` and `loadBool` respectively): `b.storeBit(true)`, `sl.loadBit()`;
- `slice`, `rawSlice`, `ascii` and `crc32` built-in functions;
- Corresponding stdlib functions for the new TVM instructions from 2023.07 and 2024.04 upgrades:  `storeBuilder` extension function and `gasConsumed`, `getComputeFee`, `getStorageFee`, `getForwardFee`, `getSimpleComputeFee`, `getSimpleForwardFee`, `getOriginalFwdFee`, `myStorageDue` functions.
- `Builder.storeMaybeRef`, `parseStdAddress` and `parseVarAddress` stdlib functions.

### PR DESCRIPTION
**Pull request by novusnota**
Wanted to help out a little, please review whenever you find convenient

### Changes

1. Added a lot of completions for all new functions, methods, extension functions, etc.
2. Added the [updated TextMate grammar](https://github.com/tact-lang/tact-sublime/blob/main/package/Tact.tmLanguage.json) for syntax highlighting*
3. Added support for the `asm` functions in the parser

### Notes

1. pegjs used in the project can be seamlessly replaced by its maintained version — [peggyjs](https://peggyjs.org) ([repo](https://github.com/peggyjs/peggy)). There are only three small steps for migration: https://github.com/peggyjs/peggy#migrating-from-pegjs

2. The current parser seems to be a tangled amalgamation of JavaScript, FunC and Tact parsers, none of which is complete nor correct. JavaScript made the biggest influence with its ASI, import...from statements, and other weird leftovers. Very tough to do anything productive with from the outside standpoint, just my 2 cents :heart: :)

3. I hope I didn't butcher the formatting and did things there right. Please, double-check and/or correct :pray: 

Closes #44

### CODE REVIEW

**Comment by logvik** [comment]
Can you add here some sample for the smart contract code that can be used to test the new features on the parser side? To test the new changes quickly we can use https://peggyjs.org/online.html

**Comment by novusnota** [comment]
@logvik thanks for the suggestion! I've refined the parser and checked that it works as intended on https://peggyjs.org/online.html. Also added a `samples/` folder (and adjusted `.vscodeignore`) and placed the first sample with `asm` functions there. They were taken from the tests of `grammar.ohm` in Tact compiler repo.

<details>
<summary>Tact code to test on https://peggyjs.org/online.html</summary>

```tact
asm fun keccak256(s: Slice): Int {
    1
    INT
    HASHEXT_KECCAK256
}

asm( -> 1 0) extends fun loadCoins(self: Slice): Int {
    LDVARUINT16
}

asm(c b) extends fun storeDict(b: Builder, c: Cell) {
    STDICT
}

asm(s len -> 1 0) extends fun loadInt(self: Slice, len: Int): Int {
    LDIX
}

asm fun checkAndRemoveAddExtensionPrefix(self: Slice): Int {
    x{02} SDBEGINSQ
}

asm fun checkAndRemoveAddExtensionPrefix() {
    -ROT
}

asm fun debugStr1() {
    "Works!" DEBUGSTR
}

asm fun debugStr2() { "Works!" }

asm fun createWord() {
    { INC }
}

/// Tests list and binding to a new regular word
asm fun createAndUseWord1(): Int {
    { INC } : incinc
    41 incinc
}

/// Tests weird formatting
asm fun createAndUseWord2(): Int { { INC
}
: incinc 41 incinc
}

/// Tests weird formatting
asm fun createAndUseWord3(): Int {
{
INC
}
:
incinc
41
incinc
}

/// Tests words with } inside of them
asm fun isIntAnInt(x: Int): Int {
    <{
        TRY:<{
            0 PUSHINT ADD DROP -1 PUSHINT
        }>CATCH<{
            2DROP 0 PUSHINT
        }>
    }>CONT 1 1 CALLXARGS
}
```

</details>

image

**Review by anton-trunov — APPROVED** [review]
LGTM! @logvik could you please leave your feedback? We would like to move on with Tact v1.5 support

**Review by logvik — APPROVED** [review]

**Comment by logvik** [comment]
> LGTM! @logvik could you please leave your feedback? We would like to move on with Tact v1.5 support

I will update the extension on the marketplace this evening. Let's publish this PR and then I will add more, just don't have a time right now to test my own additional changes careful.

**Comment by anton-trunov** [comment]
Awesome! Thanks a bunch

**Comment by logvik** [comment]
2024-10-08 09_46_01- Extension Development Host  ● asm tact - locker-contracts (Workspace) - Visual

This code is from samples/items-asm-func.tact

I think we should fix this before publishing on the marketplace.

**Comment by novusnota** [comment]
@logvik that file was to test parsers only (pegjs here and Ohm in Tact compiler) and it wasn't really valid from semantical point of view. Only syntax there mattered :)

Also, to fix this exact snippet, try removing the first `1`

**Comment by logvik** [comment]
It didn't help, but I have published because that error was related to the compiler warning, as you have been mentioned above.

**Pull request merged**
